version: '3'

services:
  bot:
    build: .
    restart: always
    volumes:
      - ./project:/app
      - ./mapping.json:/mapping.json
      - ./alerts.json:/alerts.json
    command: 'python3 bot.py'
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - bot.env
    network_mode: host
